
.section .data


# FILE GENERATED BY SEMBLELANG
#                             
# SembleLang version beta1.1.2
# By Riley
#  A Langauge designed for speed and simpli
# city. With accuracy and flexibility in mi
# nd I hand-crafted this language from the 
# ground up to provide an easy way to get i
# nto high-speed coding.



.section .data



.globl _start

_start:
	call main
	movl %eax, %ebx
	movl $1, %eax
	int $0x80
.type main, @function
main:
	pushl %ebp
	movl %esp, %ebp
	subl $4, %esp
	movl $5, %ecx

	movl %ecx, -4(%ebp) # variable x
	incl -4(%ebp)
	movl -4(%ebp), %ecx
	movl %ecx, %eax
	jmp .lmain
	.lmain:
	movl %ebp, %esp
	popl %ebp
	ret
